/**
 * Rules loading and normalization.
 *
 * Historically three rule shapes existed across the proxy and the library:
 *   1. Array format (generated by mcp-gov-wrap):
 *        { defaultPolicy?, rules: [{ service, operations: [...], permission }] }
 *   2. Legacy object format:
 *        { defaultPolicy?, services: { svc: { operations: { op: 'allow'|'deny' } } } }
 *   3. SDK nested-map (GovernedMCPServer / examples):
 *        { svc: { op: 'allow'|'deny' }, defaultPolicy? }
 *
 * `normalizeRules` accepts any of these and produces a single canonical form,
 * so callers share one matcher (`isAllowed`) instead of duplicating per-format
 * logic. `defaultPolicy` is preserved (default 'allow' for backward compat).
 */

/**
 * @typedef {'allow'|'deny'} Permission
 * @typedef {{ defaultPolicy: Permission, services: Record<string, Record<string, Permission>> }} NormalizedRules
 */

/**
 * Top-level keys that are metadata, never service names, in the nested-map
 * shape. `defaultPolicy` is our keyword and `_*` is the comment convention;
 * `services`/`rules` are NOT reserved here because format detection already
 * routes the structural variants away, so a nested-map service may legitimately
 * be named "services" or "rules" without being silently dropped.
 */
function isReservedKey(key) {
  return key === 'defaultPolicy' || key.startsWith('_');
}

/**
 * True only for the legacy { svc: { operations: { op: perm } } } shape, i.e. a
 * `services` object whose entries wrap an `operations` map. This prevents a
 * nested-map rules object with a service literally named "services" (e.g.
 * { services: { read: "deny" } }) from being misdetected as legacy and dropped.
 * @param {any} services
 * @returns {boolean}
 */
function looksLikeLegacy(services) {
  if (!services || typeof services !== 'object' || Array.isArray(services)) return false;
  return Object.values(services).some(
    (cfg) => cfg && typeof cfg === 'object' && cfg.operations && typeof cfg.operations === 'object'
  );
}

/**
 * Normalize any supported rules shape into a canonical
 * { defaultPolicy, services: { svc: { op: permission } } } form.
 * @param {any} raw - Parsed rules object (any supported format)
 * @param {Permission} [fallbackDefaultPolicy] - Used when `raw` has no defaultPolicy
 * @returns {NormalizedRules}
 */
export function normalizeRules(raw, fallbackDefaultPolicy) {
  /** @type {NormalizedRules} */
  const out = { defaultPolicy: 'allow', services: {} };

  if (!raw || typeof raw !== 'object') {
    out.defaultPolicy = fallbackDefaultPolicy === 'deny' ? 'deny' : 'allow';
    return out;
  }

  // Rules-level defaultPolicy takes precedence over any caller fallback.
  const policy = raw.defaultPolicy || fallbackDefaultPolicy;
  out.defaultPolicy = policy === 'deny' ? 'deny' : 'allow';

  const setOp = (service, op, permission) => {
    if (!service || (permission !== 'allow' && permission !== 'deny')) return;
    if (!out.services[service]) out.services[service] = {};
    out.services[service][op] = permission;
  };

  if (Array.isArray(raw.rules)) {
    // Format 1: array of { service, operations[], permission }
    for (const rule of raw.rules) {
      if (!rule || !rule.service || !Array.isArray(rule.operations)) continue;
      for (const op of rule.operations) setOp(rule.service, op, rule.permission);
    }
  } else if (looksLikeLegacy(raw.services)) {
    // Format 2: legacy { services: { svc: { operations: { op: perm } } } }
    for (const [service, cfg] of Object.entries(raw.services)) {
      const ops = cfg && cfg.operations;
      if (ops && typeof ops === 'object') {
        for (const [op, perm] of Object.entries(ops)) setOp(service, op, perm);
      }
    }
  } else {
    // Format 3: SDK nested-map { svc: { op: perm } } (skip metadata keys)
    for (const [service, cfg] of Object.entries(raw)) {
      if (isReservedKey(service)) continue;
      if (cfg && typeof cfg === 'object') {
        for (const [op, perm] of Object.entries(cfg)) setOp(service, op, perm);
      }
    }
  }

  return out;
}

/**
 * Decide whether an operation is permitted against normalized rules.
 * An explicit allow/deny for the service+operation wins; otherwise the
 * normalized defaultPolicy applies (allow unless set to 'deny').
 * @param {NormalizedRules} normalized
 * @param {string} service
 * @param {string} operation
 * @returns {boolean}
 */
export function isAllowed(normalized, service, operation) {
  const svc = normalized.services[service];
  const permission = svc && svc[operation];
  if (permission === 'allow') return true;
  if (permission === 'deny') return false;
  return normalized.defaultPolicy !== 'deny';
}
